name: .NET Web App CI

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup.NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Restore and build
        run: |
          dotnet restore
          dotnet build --no-restore

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: your_registry_name/your_image_name:latest
